--(i) Copy tables and fix them...
--copy players table...
create table players as
select * from xsales.players;
--add its primary key...
alter table players
add primary key (playerid);
--copy teams table...
create table teams as
select * from xsales.teams;
--add its primary key...
alter table teams
add primary key (teamid,year);
--copy players_teams table...
create table players_teams as
select * from xsales.players_teams;
--add its foreign keys...
ALTER TABLE players_teams
ADD FOREIGN KEY (Playerid) REFERENCES Players(Playerid)
ADD FOREIGN KEY (teamid,year) REFERENCES teams(teamid,year);
--copy allstars table...
create table allstars as
select * from xsales.allstars;
--add its primary key and its foreign key...
alter table allstars
add primary key (playerid,year)
add foreign key (playerid) references players(playerid);